#!/bin/bash

source mybashrc

echo "Compiling catalyticWall boundary condition"
cd boundary/catalyticWall
wclean
wmake
cd ../..

echo " "
echo "Compiling catalyticFoam solver"
cd solver
wclean
if [ "$OF" == 90 ];
then
    cp Make/options_9x Make/options
else
    cp Make/options_8x Make/options
fi
wmake

cd ../preprocessor-kinetic
wclean
wmake
