#!/bin/bash

source mybashrc

echo "Compiling catalyticWall boundary condition"
cd boundary/catalyticWall
wclean
wmake

echo " "
echo "Compiling catalyticFoam libraries"
cd ../../libraries
./Allwclean
./Allwmake

echo " "
echo "Compiling catalyticFoam solver"
cd ../solver
wclean
if [ "$OF" == 90 ];
then
    cp Make/options.9x Make/options
else
    cp Make/options.8x Make/options
fi
wmake

cd ../preprocessor-kinetic
wclean
wmake
